SELECT TDATE, SUM(CHANGE_OF_CO2)
FROM
	(
	SELECT TDATE, HID, VID, TMILES, EPATMPG, TMILES/EPATMPG * 0.00887 AS GAS_CO2, 
	CASE 	WHEN TMILES <= 20 THEN TMILES/EPATMPG * 33.1/3.0 * D.CO2_KWH 
		WHEN TMILES >20 THEN 20/EPATMPG * 33.1/3.0 * D.CO2_KWH
	END AS ELE_CO2
	, 
	CASE 	WHEN TMILES <= 20 THEN TMILES/EPATMPG * 33.1/3.0 * D.CO2_KWH - TMILES/EPATMPG * 0.00887
		WHEN TMILES >20 THEN 20/EPATMPG * 33.1/3.0 * D.CO2_KWH - TMILES/EPATMPG * 0.00887
	END AS CHANGE_OF_CO2 
			
	FROM

		((
			(SELECT HOUSEID AS HID, VEHID AS VID,TRPMILES AS TMILES,TDAYDATE AS TDATE, STRTTIME AS STIME 
			FROM DAY
			GROUP BY HOUSEID,VEHID,TRPMILES,TDAYDATE, STRTTIME
			HAVING cast(VEHID as integer) >= 1
			) A 
			/* A : GET A RESULT FOR EACH TRIP WHICH BELONGS TO HOUSEHOLD VEHICLES */
			INNER JOIN VEHICLE B
			ON A.HID = B.HOUSEID AND A.VID = B.VEHID
		)C /* C : ADD MATCHED EPATMPG TO THE TABLE A*/
		

		INNER JOIN

		(SELECT A.YYYYMM, A.VALUE / B.VALUE AS CO2_KWH
		FROM EIA_ELECTRIC A, EIA_MKWH B
		WHERE A.MSN = 'TXEIEUS' AND B.MSN = 'ELETPUS' AND A.YYYYMM = B.YYYYMM) D

		ON C.TDATE = D.YYYYMM

		)GROUP BY C.HID, C.VID, C.TMILES, C.TDATE, C.EPATMPG, D.CO2_KWH, C.STIME
		ORDER BY C.TDATE, C.STIME, C.HID, C.VID, C.TMILES 
	) E
	GROUP BY TDATE
	ORDER BY TDATE

